package frc.robot.constants.drivetrain;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Voltage;
import frc.robot.subsystems.DrivetrainSubsystem;

// Generated by the Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class DevbotTunerConstants {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with
    // the output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    public static final Slot0Configs DEFAULT_STEER_CONSTANTS = new Slot0Configs()
            .withKP(35).withKI(0).withKD(0.25)
            .withKS(0.045).withKV(2.4).withKA(0.125)
            .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control output type
    // specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    public static final Slot0Configs DEFAULT_DRIVE_CONSTANTS = new Slot0Configs()
            .withKP(0.15).withKI(0).withKD(0)
            .withKS(0.073922).withKV(2.4363).withKA(0.062414);

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType STEER_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType DRIVE_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement DRIVE_MOTOR_TYPE = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement STEER_MOTOR_TYPE = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType STEER_FEEDBACK_TYPE = SteerFeedbackType.FusedCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current SLIP_CURRENT = Amps.of(120.0);

    // Initial configs for the drive and steer motors and the azimuth encoder; these
    // cannot be null. Some configs will be overwritten; check the
    // `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration DRIVE_INITIAL_CONFIGS = new TalonFXConfiguration();
    private static final TalonFXConfiguration STEER_INITIAL_CONFIGS = new TalonFXConfiguration()
            .withCurrentLimits(
                    new CurrentLimitsConfigs()
                            // Swerve azimuth does not require much torque output, so we can set a
                            // relatively low stator current limit to help avoid brownouts without impacting
                            // performance.
                            .withStatorCurrentLimit(Amps.of(60))
                            .withStatorCurrentLimitEnable(true));
    private static final CANcoderConfiguration ENCODER_INITIAL_CONFIGS = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration PIGEON_CONFIGS = null;

    // CAN bus that the devices are located on.
    // All swerve devices must share the same CAN bus
    public static final CANBus CAN_BUS = new CANBus("rio", "./logs/example.hoot"); // TODO - physically swap to CANivore

    // Theoretical free speed (m/s) at 12 V applied output.
    // This needs to be tuned to your individual robot
    public static final LinearVelocity SPEED_AT_12_VOLTS = MetersPerSecond.of(12 / DEFAULT_DRIVE_CONSTANTS.kV);

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    private static final double COUPLE_RATIO = 2.417;

    public static final double DRIVE_GEAR_RATIO = 6.746031746031747;
    public static final double STEER_GEAR_RATIO = 21.428571428571427;
    public static final Distance WHEEL_RADIUS = Inches.of(2);

    private static final boolean INVERT_LEFT_SIDE = false;
    private static final boolean INVERT_RIGHT_SIDE = true;

    private static final int PIGEON_ID = 13;

    // These are only used for simulation
    private static final MomentOfInertia STEER_MOI = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia DRIVE_MOI = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage STEER_FRICTION_VOLTS = Volts.of(0.2);
    private static final Voltage DRIVE_FRICTION_VOLTS = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DRIVETRAIN_CONSTANTS = new SwerveDrivetrainConstants()
            .withCANBusName(CAN_BUS.getName())
            .withPigeon2Id(PIGEON_ID)
            .withPigeon2Configs(PIGEON_CONFIGS);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> CONSTANT_CREATOR = new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(DRIVE_GEAR_RATIO)
            .withSteerMotorGearRatio(STEER_GEAR_RATIO)
            .withCouplingGearRatio(COUPLE_RATIO)
            .withWheelRadius(WHEEL_RADIUS)
            .withSteerMotorGains(DEFAULT_STEER_CONSTANTS)
            .withDriveMotorGains(DEFAULT_DRIVE_CONSTANTS)
            .withSteerMotorClosedLoopOutput(STEER_CLOSED_LOOP_OUTPUT)
            .withDriveMotorClosedLoopOutput(DRIVE_CLOSED_LOOP_OUTPUT)
            .withSlipCurrent(SLIP_CURRENT)
            .withSpeedAt12Volts(SPEED_AT_12_VOLTS)
            .withDriveMotorType(DRIVE_MOTOR_TYPE)
            .withSteerMotorType(STEER_MOTOR_TYPE)
            .withFeedbackSource(STEER_FEEDBACK_TYPE)
            .withDriveMotorInitialConfigs(DRIVE_INITIAL_CONFIGS)
            .withSteerMotorInitialConfigs(STEER_INITIAL_CONFIGS)
            .withEncoderInitialConfigs(ENCODER_INITIAL_CONFIGS)
            .withSteerInertia(STEER_MOI)
            .withDriveInertia(DRIVE_MOI)
            .withSteerFrictionVoltage(STEER_FRICTION_VOLTS)
            .withDriveFrictionVoltage(DRIVE_FRICTION_VOLTS);

    // Front Left
    private static final int FL_DRIVE_ID = 6;
    private static final int FL_STEER_ID = 5;
    private static final int FL_ENCODER_ID = 11;
    private static final Angle FL_ENCODER_OFFSET = Rotations.of(-0.146240234375);
    private static final boolean FL_STEER_INVERT = true;
    private static final boolean FL_ENCODER_INVERT = false;

    public static final Slot0Configs FL_STEER_CONSTANTS = DEFAULT_STEER_CONSTANTS
            .withKS(0.033023).withKV(2.391).withKA(0.10173);
    public static final Slot0Configs FL_DRIVE_CONSTANTS = DEFAULT_DRIVE_CONSTANTS
            .withKS(0.0669).withKV(2.4304).withKA(0.10155);

    public static final Distance FL_XPOS = Inches.of(12.5);
    public static final Distance FL_YPOS = Inches.of(12.5);

    // Front Right
    private static final int FR_DRIVE_ID = 8;
    private static final int FR_STEER_ID = 7;
    private static final int FR_ENCODER_ID = 12;
    private static final Angle FR_ENCODER_OFFSET = Rotations.of(-0.308350);
    private static final boolean FR_STEER_INVERT = true;
    private static final boolean FR_ENCODER_INVERT = false;

    public static final Slot0Configs FR_STEER_CONSTANTS = DEFAULT_STEER_CONSTANTS
            .withKS(0.074886).withKV(2.3641).withKA(0.1937);
    public static final Slot0Configs FR_DRIVE_CONSTANTS = DEFAULT_DRIVE_CONSTANTS
            .withKS(0.0640).withKV(2.4413).withKA(0.090446);

    public static final Distance FR_XPOS = Inches.of(12.5);
    public static final Distance FR_YPOS = Inches.of(-12.5);

    // Back Left
    private static final int BL_DRIVE_ID = 4;
    private static final int BL_STEER_ID = 3;
    private static final int BL_ENCODER_ID = 10;
    private static final Angle BL_ENCODER_OFFSET = Rotations.of(0.048583984375);
    private static final boolean BL_STEER_INVERT = true;
    private static final boolean BL_ENCODER_INVERT = false;

    public static final Slot0Configs BL_STEER_CONSTANTS = DEFAULT_STEER_CONSTANTS
            .withKS(0.078373).withKV(2.3735).withKA(0.15668);
    public static final Slot0Configs BL_DRIVE_CONSTANTS = DEFAULT_DRIVE_CONSTANTS
            .withKS(0.0795).withKV(2.3735).withKA(0.065728);

    public static final Distance BL_XPOS = Inches.of(-12.5);
    public static final Distance BL_YPOS = Inches.of(12.5);

    // Back Right
    private static final int BR_DRIVE_ID = 2;
    private static final int BR_STEER_ID = 1;
    private static final int BR_ENCODER_ID = 9;
    private static final Angle BR_ENCODER_OFFSET = Rotations.of(0.26416015625);
    private static final boolean BR_STEER_INVERT = true;
    private static final boolean BR_ENCODER_INVERT = false;

    public static final Slot0Configs BR_STEER_CONSTANTS = DEFAULT_STEER_CONSTANTS
            .withKS(0.052225).withKV(2.3774).withKA(0.10977);
    public static final Slot0Configs BR_DRIVE_CONSTANTS = DEFAULT_DRIVE_CONSTANTS
            .withKS(0.0784).withKV(2.447).withKA(0.067734);

    public static final Distance BR_XPOS = Inches.of(-12.5);
    public static final Distance BR_YPOS = Inches.of(-12.5);

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FL_CONSTANTS = CONSTANT_CREATOR
            .createModuleConstants(
                    FL_STEER_ID, FL_DRIVE_ID, FL_ENCODER_ID, FL_ENCODER_OFFSET,
                    FL_XPOS, FL_YPOS, INVERT_LEFT_SIDE, FL_STEER_INVERT,
                    FL_ENCODER_INVERT)
            .withSteerMotorGains(FL_STEER_CONSTANTS);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FR_CONSTANTS = CONSTANT_CREATOR
            .createModuleConstants(
                    FR_STEER_ID, FR_DRIVE_ID, FR_ENCODER_ID, FR_ENCODER_OFFSET,
                    FR_XPOS, FR_YPOS, INVERT_RIGHT_SIDE, FR_STEER_INVERT,
                    FR_ENCODER_INVERT)
            .withSteerMotorGains(FR_STEER_CONSTANTS);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BL_CONSTANTS = CONSTANT_CREATOR
            .createModuleConstants(
                    BL_STEER_ID, BL_DRIVE_ID, BL_ENCODER_ID, BL_ENCODER_OFFSET,
                    BL_XPOS, BL_YPOS, INVERT_LEFT_SIDE, BL_STEER_INVERT,
                    BL_ENCODER_INVERT)
            .withSteerMotorGains(BL_STEER_CONSTANTS);
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BR_CONSTANTS = CONSTANT_CREATOR
            .createModuleConstants(
                    BR_STEER_ID, BR_DRIVE_ID, BR_ENCODER_ID, BR_ENCODER_OFFSET,
                    BR_XPOS, BR_YPOS, INVERT_RIGHT_SIDE, BR_STEER_INVERT,
                    BR_ENCODER_INVERT)
            .withSteerMotorGains(BR_STEER_CONSTANTS);

    /**
     * Creates a CommandSwerveDrivetrain instance.
     * This should only be called once in your robot program,.
     */
    public static DrivetrainSubsystem createDrivetrain() {
        return new DrivetrainSubsystem(
                DRIVETRAIN_CONSTANTS, FL_CONSTANTS, FR_CONSTANTS, BL_CONSTANTS, BR_CONSTANTS);
    }

    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected
     * device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct the devices themselves. If they need the devices, they can access
         * them through getters in the classes.
         *
         * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
         * @param modules             Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, modules);
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct the devices themselves. If they need the devices, they can access
         * them through getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                double odometryUpdateFrequency,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, odometryUpdateFrequency, modules);
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not
         * construct the devices themselves. If they need the devices, they can access
         * them through getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve
         *                                  drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz
         *                                  on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry
         *                                  calculation
         *                                  in the form [x, y, theta]ᵀ, with units in
         *                                  meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision
         *                                  calculation
         *                                  in the form [x, y, theta]ᵀ, with units in
         *                                  meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public TunerSwerveDrivetrain(
                SwerveDrivetrainConstants drivetrainConstants,
                double odometryUpdateFrequency,
                Matrix<N3, N1> odometryStandardDeviation,
                Matrix<N3, N1> visionStandardDeviation,
                SwerveModuleConstants<?, ?, ?>... modules) {
            super(
                    TalonFX::new, TalonFX::new, CANcoder::new,
                    drivetrainConstants, odometryUpdateFrequency,
                    odometryStandardDeviation, visionStandardDeviation, modules);
        }
    }
}
